### PR TITLE
Expose filename of audio_file

### PR DESCRIPTION
**Pull request by robbevp**
Will be necessary for Accentor/web#33

### CODE REVIEW

**Comment by charvp** [comment]
I feel like this information should only be available to moderators. It exposes the underlying file structure to unprivileged users right now.

**Comment by robbevp** [comment]
> I feel like this information should only be available to moderators. It exposes the underlying file structure to unprivileged users right now.

I've updated the MR. I suppose we will rename the new serializer if/when we want to expose other properties to mod+ only - but would only do that then

**Comment by charvp** [comment]
> I've updated the PR. I suppose we will rename the new serializer if/when we want to expose other properties to mod+ only - but would only do that then

I would rename the serializer right now. Something like ModeratorTrackSerializer or similar. It makes the purpose more clear, IMO. Also, could you add some tests? Doesn't seem to hard, and I would like it if we raised the project coverage with every PR. Coverage isn't everything, but if we add meaningful tests every time, it should mean something.

**Comment by robbevp** [comment]
@charvp There is only a small difference in coverage, but at least all changes are covered.
I've renamed the serializer `TrackModerator` - not the best name, but it had the benefit that the file was sorted alongside the track serializer

**Pull request merged**
