### PR TITLE
Rename merge params to `source_id`

### PR DESCRIPTION
**Pull request by robbevp**
Makes the merge param consistent accross all controllers.
Necessary for the` api-client-js` to work

- [x] I've ~~added~~ updated tests relevant to my changes.

### CODE REVIEW

**Review by chvp — COMMENTED** [review]
I'm not sure about the `old` naming. There is no clear time order when merging. (I'm not actually sure if it's the older item that will be removed when merging, but my intuition says no.)

**Comment by robbevp** [comment]
The second param (so `old_id` or `other_MODEL_id`) is the item that gets destroyed.
I would like to have a param that makes it clear which item gets destroyed, but agree that `old_id` isn't fully clear either. Any suggestions?

**Comment by chvp** [comment]
`removed_id` maybe? It's not perfect, since the item isn't removed yet at the time of calling, but `to_remove_id` feels a little clunky.

**Comment by chvp** [comment]
Also, can you open a PR on web that incorporates these changes? I'd like to merge them at the same time.

**Comment by robbevp** [comment]
Maybe `source_id`? (where the first id would be the `target`)

**Comment by chvp** [comment]
`source_id` sounds good.

**Review by chvp — APPROVED** [review]

**Pull request merged**
